(function(){
'use strict';
var state={password:null,activeTab:'results',teams:{},questions:[],groupMatches:[]};
var TABS=[{id:'results',label:'Resultater'},{id:'questions',label:'Ekstraspørsmål'},{id:'answers',label:'Fasit'},{id:'scoring',label:'Poengregler'},{id:'settings',label:'Innstillinger'},{id:'recalc',label:'Beregn på nytt'}];

async function attemptLogin(){var pw=document.getElementById('pw-input').value;var errEl=document.getElementById('pw-error');errEl.textContent='';if(!pw){errEl.textContent='Oppgi passord';return;}try{var ok=await API.verifyAdmin(pw);if(!ok){errEl.textContent='Feil passord';return;}state.password=pw;sessionStorage.setItem('wc26_admin_pw',pw);document.getElementById('login').classList.add('hidden');document.getElementById('panel').classList.remove('hidden');renderPanel();await loadBaseData();}catch(err){errEl.textContent='Feil: '+err.message;}}
window.attemptLogin=attemptLogin;
document.addEventListener('DOMContentLoaded',function(){var saved=sessionStorage.getItem('wc26_admin_pw');if(saved){document.getElementById('pw-input').value=saved;attemptLogin();}document.getElementById('pw-input').addEventListener('keypress',function(e){if(e.key==='Enter')attemptLogin();});});

async function loadBaseData(){try{var teams=await API.getTeams();state.teams={};for(var i=0;i<teams.length;i++)state.teams[teams[i].team_code]=teams[i];state.questions=await API.getQuestions();var r=await supabase.from('results_group').select('*').order('match_id');state.groupMatches=r.data||[];renderTabContent();}catch(err){toast('Feil: '+err.message,'err');}}

function renderPanel(){document.getElementById('tabs').innerHTML=TABS.map(function(t){return '<button class="tab '+(t.id===state.activeTab?'active':'')+'" onclick="switchTab(\''+t.id+'\')">'+t.label+'</button>';}).join('');}
window.switchTab=function(id){state.activeTab=id;renderPanel();renderTabContent();};
function renderTabContent(){var c=document.getElementById('tab-content');switch(state.activeTab){case 'results':return renderResultsTab(c);case 'questions':return renderQuestionsTab(c);case 'answers':return renderAnswersTab(c);case 'scoring':return renderScoringTab(c);case 'settings':return renderSettingsTab(c);case 'recalc':return renderRecalcTab(c);}}

function renderResultsTab(c){var groups=['A','B','C','D','E','F','G','H','I','J','K','L'];var html='<div class="panel"><h3>Gruppespill-resultater</h3><p class="panel-desc">Skriv inn sluttresultat. Trykk Lagre for å oppdatere.</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:1rem;">';for(var gi=0;gi<groups.length;gi++){var g=groups[gi];var matches=state.groupMatches.filter(function(m){return m.group_code===g;});var rows=matches.map(function(m){var ht=state.teams[m.home_team];var at=state.teams[m.away_team];return '<div class="match-row" data-mid="'+m.match_id+'"><span class="match-id-cell">#'+m.match_id+'</span><span class="match-team-cell">'+(ht?ht.flag+' '+ht.name_no:m.home_team)+'</span><input class="match-score" type="number" min="0" data-field="home" value="'+(m.home_score!=null?m.home_score:'')+'" style="width:50px;"><span class="match-vs">-</span><input class="match-score" type="number" min="0" data-field="away" value="'+(m.away_score!=null?m.away_score:'')+'" style="width:50px;"><span class="match-team-cell">'+(at?at.flag+' '+at.name_no:m.away_team)+'</span><span class="match-status">'+(m.status==='final'?'✓':'')+'</span></div>';}).join('');html+='<div style="background:var(--paper);border:1px solid var(--line);border-radius:6px;padding:0.75rem;"><div style="font-family:Bricolage Grotesque,sans-serif;font-weight:800;margin-bottom:0.5rem;">Gruppe '+g+'</div>'+rows+'</div>';}
html+='</div><button class="btn btn-primary" style="margin-top:1rem;" onclick="saveGroupResults()">Lagre alle gruppekamper</button></div>';c.innerHTML=html;}

window.saveGroupResults=async function(){var rows=document.querySelectorAll('[data-mid]');var saved=0;for(var i=0;i<rows.length;i++){var row=rows[i];var mid=parseInt(row.dataset.mid);var hs=row.querySelector('[data-field="home"]').value;var as=row.querySelector('[data-field="away"]').value;if(hs!==''&&as!==''){try{await API.adminUpdateGroupResult(state.password,mid,parseInt(hs),parseInt(as));saved++;}catch(err){toast('Feil #'+mid+': '+err.message,'err');}}}toast(saved+' kamper lagret','ok');var r=await supabase.from('results_group').select('*').order('match_id');state.groupMatches=r.data||[];renderTabContent();};

function renderQuestionsTab(c){var rows=state.questions.map(function(q){return '<tr><td style="font-family:JetBrains Mono,monospace;">'+q.q_id+'</td><td>'+escapeHTML(q.question_no)+'</td><td>'+q.answer_type+'</td><td style="font-weight:700;">'+q.points+'p</td><td>'+q.round+'</td></tr>';}).join('');c.innerHTML='<div class="panel"><h3>Ekstraspørsmål</h3><p class="panel-desc">Rediger direkte i Supabase Table Editor → extra_questions</p><table class="admin-table"><thead><tr><th>ID</th><th>Spørsmål</th><th>Type</th><th>Poeng</th><th>Runde</th></tr></thead><tbody>'+rows+'</tbody></table></div>';}

function renderAnswersTab(c){var rows=state.questions.map(function(q){return '<tr><td style="font-family:JetBrains Mono,monospace;">#'+q.q_id+'</td><td>'+escapeHTML(q.question_no)+'</td><td style="width:200px;"><input type="'+(q.answer_type==='number'?'number':'text')+'" data-qid="'+q.q_id+'" placeholder="Svar…"></td><td><button class="btn btn-ghost" style="padding:0.375rem 0.625rem;" onclick="saveOneAnswer('+q.q_id+')">Lagre</button></td></tr>';}).join('');c.innerHTML='<div class="panel"><h3>Offisielle svar (fasit)</h3><table class="admin-table"><thead><tr><th>ID</th><th>Spørsmål</th><th>Svar</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div>';(async function(){var r=await supabase.from('official_answers').select('*');if(r.data)for(var i=0;i<r.data.length;i++){var inp=document.querySelector('[data-qid="'+r.data[i].q_id+'"]');if(inp)inp.value=r.data[i].answer_value||'';}})();}
window.saveOneAnswer=async function(qId){var inp=document.querySelector('[data-qid="'+qId+'"]');try{await API.adminUpdateAnswer(state.password,qId,inp.value);toast('Svar #'+qId+' lagret','ok');}catch(err){toast('Feil: '+err.message,'err');}};

function renderScoringTab(c){c.innerHTML='<div class="panel"><h3>Poengregler</h3><p class="panel-desc">Rediger i Supabase Table Editor → scoring_config</p><div id="scoring-values">Laster…</div></div>';(async function(){var cfg=await API.getScoringConfig();var el=document.getElementById('scoring-values');el.innerHTML=Object.entries(cfg).map(function(kv){return '<div style="display:flex;justify-content:space-between;padding:0.375rem 0;border-bottom:1px solid var(--line);"><span style="font-family:JetBrains Mono,monospace;font-size:0.8125rem;">'+kv[0]+'</span><span style="font-weight:700;">'+kv[1]+'</span></div>';}).join('');})();}

function renderSettingsTab(c){c.innerHTML='<div class="panel"><h3>Innstillinger</h3><div style="margin-bottom:1rem;"><label style="display:block;font-size:0.8125rem;font-weight:600;margin-bottom:0.375rem;">Frist (ISO UTC)</label><input type="text" id="set-deadline" placeholder="2026-06-11T15:00:00Z"></div><div style="margin-bottom:1rem;"><label style="display:block;font-size:0.8125rem;font-weight:600;margin-bottom:0.375rem;">Gjeldende runde</label><select id="set-round"><option>PRE</option><option>GROUP</option><option>R32</option><option>R16</option><option>QF</option><option>SF</option><option>F</option><option>COMPLETE</option></select></div><button class="btn btn-primary" onclick="saveSettings()">Lagre</button></div>';}
window.saveSettings=async function(){try{var dl=document.getElementById('set-deadline').value;var rnd=document.getElementById('set-round').value;if(dl)await API.adminUpdateSetting(state.password,'deadline_iso',dl);if(rnd)await API.adminUpdateSetting(state.password,'current_round',rnd);toast('Lagret','ok');}catch(err){toast('Feil: '+err.message,'err');}};

function renderRecalcTab(c){c.innerHTML='<div class="recalc-card"><div style="font-family:JetBrains Mono,monospace;font-size:0.6875rem;letter-spacing:0.2em;opacity:0.7;margin-bottom:0.5rem;">MASTER RECALCULATE</div><h3 style="font-family:Bricolage Grotesque,sans-serif;font-size:1.5rem;margin-bottom:0.75rem;font-weight:800;">Regn ut alle poeng på nytt</h3><p style="opacity:0.8;margin-bottom:1.5rem;font-size:0.9375rem;">Henter all data → kjører poengberegning → skriver tilbake til databasen.</p><button class="btn btn-accent" id="btn-recalc" onclick="doRecalc()">⚡ Start beregning</button><div id="recalc-log" style="margin-top:1.25rem;font-family:JetBrains Mono,monospace;font-size:0.8125rem;text-align:left;max-width:500px;margin:1rem auto 0;"></div></div>';}

window.doRecalc=async function(){var btn=document.getElementById('btn-recalc');var log=document.getElementById('recalc-log');btn.disabled=true;btn.innerHTML='<span class="loading"></span> Beregner…';log.innerHTML='';function L(s){log.innerHTML+=s+'<br>';}
try{var t0=Date.now();L('→ Henter data fra Supabase…');var allData=await API.adminGetScoringData(state.password);var parts=allData.participants||[];L('  '+parts.length+' deltakere, '+(allData.results_group||[]).length+' gruppekamper');

L('→ Beregner gruppetabeller…');var groupKeys=['A','B','C','D','E','F','G','H','I','J','K','L'];var allGroupTables={};var groupTableArrays=[];var teamsByGroup={};var allTeams=await API.getTeams();for(var i=0;i<allTeams.length;i++){var t=allTeams[i];if(!teamsByGroup[t.group_code])teamsByGroup[t.group_code]=[];teamsByGroup[t.group_code].push(t.team_code);}
var groupResults=allData.results_group||[];for(var gi=0;gi<groupKeys.length;gi++){var g=groupKeys[gi];var teams=teamsByGroup[g]||[];var matches=groupResults.filter(function(m){return m.group_code===g;}).map(function(m){return{home:m.home_team,away:m.away_team,home_score:m.home_score,away_score:m.away_score};});var table=computeGroupTable(g,teams,matches);allGroupTables[g]=table;groupTableArrays.push(table);}

L('→ Rangerer 3.-plasser…');var thirdPlace=rankThirdPlacedTeams(groupTableArrays);L('  Kvalifiserte: '+(thirdPlace.qualifying_groups.join(', ')||'(ingen ennå)'));

var actualGroups={};for(var gc in allGroupTables)actualGroups[gc]=allGroupTables[gc].map(function(t){return t.team;});
var actualKO={R32:[],R16:[],QF:[],SF:[],F:[],W:[]};var koRes=allData.results_knockout||[];for(var ki=0;ki<koRes.length;ki++){var r=koRes[ki];if(r.winner){var rnd=r.round==='3rd'?'SF':r.round;if(r.home_team&&actualKO[rnd])actualKO[rnd].push(r.home_team);if(r.away_team&&actualKO[rnd])actualKO[rnd].push(r.away_team);if(r.round==='F')actualKO.W.push(r.winner);}}
for(var k in actualKO)actualKO[k]=[...new Set(actualKO[k])];

var actuals={groups:actualGroups,thirds:thirdPlace.best8.map(function(t){return t.team;}),knockout:actualKO};
var config={};var sc=allData.scoring_config||{};for(var sk in sc){var v=sc[sk];if(v==='true')v=true;else if(v==='false')v=false;else if(!isNaN(Number(v))&&v!=='')v=Number(v);config[sk]=v;}
var questions=(allData.extra_questions||[]).map(function(q){return{q_id:q.q_id,answer_type:q.answer_type,points:q.points};});
var officialAnswers={};var oa=allData.official_answers||[];for(var oi=0;oi<oa.length;oi++)officialAnswers[oa[oi].q_id]=oa[oi].answer_value;

L('→ Beregner poeng…');var predGroups=allData.predictions_groups||[];var predThirds=allData.predictions_thirds||[];var predKO=allData.predictions_knockout||[];var predExtras=allData.predictions_extras||[];
var pgByPid={};for(var pi=0;pi<predGroups.length;pi++){var pg=predGroups[pi];if(!pgByPid[pg.participant_id])pgByPid[pg.participant_id]={};pgByPid[pg.participant_id][pg.group_code]=[pg.pos1_team,pg.pos2_team,pg.pos3_team,pg.pos4_team];}
var ptByPid={};for(var ti=0;ti<predThirds.length;ti++){try{ptByPid[predThirds[ti].participant_id]=JSON.parse(predThirds[ti].picks_json);}catch(e){ptByPid[predThirds[ti].participant_id]=[];}}
var pkByPid={};for(var ki2=0;ki2<predKO.length;ki2++){var pk=predKO[ki2];if(!pkByPid[pk.participant_id])pkByPid[pk.participant_id]={R32:[],R16:[],QF:[],SF:[],F:[],W:[]};if(pkByPid[pk.participant_id][pk.round])pkByPid[pk.participant_id][pk.round].push(pk.predicted_team);}
var peByPid={};for(var ei=0;ei<predExtras.length;ei++){var pe=predExtras[ei];if(!peByPid[pe.participant_id])peByPid[pe.participant_id]={};peByPid[pe.participant_id][pe.q_id]=pe.answer_value;}

var scored=[];for(var si=0;si<parts.length;si++){var p=parts[si];var prediction={groups:pgByPid[p.participant_id]||{},thirds:ptByPid[p.participant_id]||[],knockout:pkByPid[p.participant_id]||{R32:[],R16:[],QF:[],SF:[],F:[],W:[]},extras:peByPid[p.participant_id]||{}};var scores=computeParticipantScore(prediction,actuals,questions,officialAnswers,config);scored.push({participant_id:p.participant_id,name:p.full_name,company:p.company,department:p.department,scores:scores});}

var leaderboard=buildLeaderboard(scored);L('  '+leaderboard.length+' deltakere rangert');if(leaderboard.length>0)L('  Leder: '+leaderboard[0].name+' ('+leaderboard[0].scores.total+'p)');

L('→ Skriver til database…');var scoresData=leaderboard.map(function(p){return{participant_id:p.participant_id,rank:p.rank,full_name:p.name,company:p.company,department:p.department,total:p.scores.total,total_no_extras:p.scores.total_no_extras,group_pts:p.scores.group_pts,third_pts:p.scores.third_pts,r32_pts:p.scores.R32_pts,r16_pts:p.scores.R16_pts,qf_pts:p.scores.QF_pts,sf_pts:p.scores.SF_pts,f_pts:p.scores.F_pts,w_pts:p.scores.W_pts,extras_pts:p.scores.extras_pts,group_sweeps:p.scores.group_sweeps};});
await API.adminWriteScores(state.password,scoresData);var elapsed=((Date.now()-t0)/1000).toFixed(1);L('');L('✓ Ferdig på '+elapsed+'s');toast('Beregning fullført','ok');}catch(err){L('');L('✗ Feil: '+err.message);toast('Feil: '+err.message,'err');}finally{btn.disabled=false;btn.innerHTML='⚡ Start beregning';}};

function toast(msg,type){var el=document.createElement('div');el.className='toast '+(type||'');el.textContent=msg;document.body.appendChild(el);setTimeout(function(){el.remove();},3000);}
function escapeHTML(s){if(s==null)return '';return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
})();
